# Generated by Django 5.2 on 2025-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotChannels',
        ),
        migrations.AlterModelOptions(
            name='botsagent',
            options={'ordering': ['-started_date'], 'verbose_name': 'Bot Agent', 'verbose_name_plural': 'Bot Agents'},
        ),
        migrations.AddField(
            model_name='botsagent',
            name='channels',
            field=models.ManyToManyField(related_name='bots', to='channels.channel'),
        ),
    ]
