# Generated by Django 5.2 on 2025-04-24 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotsAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('is_active_subscription', models.BooleanField(default=0)),
                ('is_direct_start', models.BooleanField(default=0)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.CharField(blank=True, max_length=255, null=True)),
                ('scrape_status', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_message', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bots_logo/')),
                ('fine_tune_stage', models.IntegerField(default=0)),
                ('custom_persona', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='dashboard.botsagent')),
            ],
        ),
    ]
