# Generated by Django 5.2 on 2025-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessages',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='botsagent',
            name='user',
        ),
        migrations.DeleteModel(
            name='BotChannels',
        ),
        migrations.DeleteModel(
            name='BotMessages',
        ),
        migrations.DeleteModel(
            name='BotsAgent',
        ),
    ]
