# Generated by Django 5.2 on 2025-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botchannels',
            options={'verbose_name': 'Bot Channel', 'verbose_name_plural': 'Bot Channels'},
        ),
        migrations.AlterModelOptions(
            name='botsagent',
            options={'verbose_name': 'Bot Agent', 'verbose_name_plural': 'Bot Agents'},
        ),
        migrations.RemoveField(
            model_name='botchannels',
            name='bot',
        ),
        migrations.AddField(
            model_name='botsagent',
            name='channels',
            field=models.ManyToManyField(related_name='bots', to='dashboard.botchannels'),
        ),
    ]
