# Generated by Django 5.2 on 2025-04-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_botchannels_options_alter_botsagent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsagent',
            name='channels',
        ),
    ]
