# Generated by Django 5.2 on 2025-04-24 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_botsagent_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsagent',
            name='agent_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
