# Generated by Django 5.2 on 2025-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_botsagent_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsagent',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
