# Generated by Django 5.2 on 2025-04-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_botmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessages',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.botsagent'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botmessages',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
