# Generated by Django 5.2 on 2025-04-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmessages',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bot Message', 'verbose_name_plural': 'Bot Messages'},
        ),
        migrations.AlterField(
            model_name='botmessages',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='channels.channel'),
        ),
    ]
