# Generated by Django 5.2 on 2025-04-29 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sharing_records', to='bots.botsagent')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_by_me', to=settings.AUTH_USER_MODEL)),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_with_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharing Center',
                'verbose_name_plural': 'Sharing Centers',
                'unique_together': {('primary_user', 'shared_user', 'bot')},
            },
        ),
    ]
